DATASET = "ibl_brainwide_map_qc"

RAW_DIR = Path(config["RAW_DIR"]) / "ibl_reproducible_ephys_2022"
PROCESSED_DIR = Path(config["PROCESSED_DIR"]) / DATASET
PIPELINE_DIR = Path(workflow.basedir)

with open(PIPELINE_DIR / "eids.txt") as fh:
    EIDS = [line.strip() for line in fh]

rule prepare_data:
    output:
        f"{PROCESSED_DIR}/{{eid}}.h5",
    shell:
        f"""
        python {PIPELINE_DIR}/prepare_data.py --raw_dir {RAW_DIR} --output_dir {PROCESSED_DIR} --eid {{wildcards.eid}}
        """

rule all:
    input:
        expand(f"{PROCESSED_DIR}/{{eid}}.h5", eid=EIDS)
