############################################################
# Allen Brain Observatory - Visual Coding Neuropixels (2019)
############################################################

DATASET = "allen_vc_2019_vis"

RAW_DIR = Path(config["RAW_DIR"]) / "allen_visual_coding_neuropixels_2019"
PROCESSED_DIR = Path(config["PROCESSED_DIR"]) / DATASET
PIPELINE_DIR = Path(workflow.basedir)

with open(PIPELINE_DIR / "session_ids.txt") as fh:
    SESSION_IDS = [line.strip() for line in fh]

rule prepare_data:
    output:
        f"{PROCESSED_DIR}/{{session_id}}.h5",
    shell: 
        f"""
        python {PIPELINE_DIR}/prepare_data.py --raw_dir {RAW_DIR} --processed_dir {PROCESSED_DIR} --session_id {{wildcards.session_id}}
        """

rule all:
    input:
        expand(f"{PROCESSED_DIR}/{{session_id}}.h5", session_id=SESSION_IDS)