"""
Allen VBN optotagging validation

To be ran after generating Allen VBN 2022 session-level HDF5 files
and the neuron metadata CSV. 

Test suite covers:
-> genotype labels
-> PSTH binning
-> saved unit labels
-> global label counts
-> metadata propagation

"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator

import h5py
import numpy as np
import pandas as pd
from temporaldata import Data


DEFAULT_BRAINSET_ID = "allen_vbn_2022"
DEFAULT_METADATA_CSV = "allen_vbn_2022.csv"
ALLOWED_CELL_TYPES = {"wt", "Sst", "Vip"}
NON_WT_CELL_TYPES = {"Sst", "Vip"}
REQUIRED_UNIT_FIELDS = {"cre_positive", "optotagged_cell_type"}
REQUIRED_METADATA_FIELDS = {"id", "optotagged_cell_type"}
DEFAULT_MAX_POSITIVE_FRACTION = 0.75


def repo_root() -> Path:
    """Return the repository root independent of the current working directory."""
    return Path(__file__).resolve().parents[2]


PIPELINE_DIR = repo_root() / "preprocess" / "allen_vbn_2022_vis"
sys.path.insert(0, str(PIPELINE_DIR))

from session_extractor import make_population_psth, standardize_genotype  # noqa: E402


@dataclass
class OptotaggingSummary:
    """Aggregated optotagging counts from processed session HDF5 files."""

    session_count: int = 0
    unit_count: int = 0
    genotype_session_counts: Counter[str] = field(default_factory=Counter)
    genotype_unit_counts: Counter[str] = field(default_factory=Counter)
    cell_type_counts: Counter[str] = field(default_factory=Counter)
    genotype_cell_type_counts: dict[str, Counter[str]] = field(
        default_factory=lambda: defaultdict(Counter)
    )


def print_ok(message: str) -> None:
    print(f"[ok] {message}")


def default_processed_dir() -> Path:
    """
    Resolve the default processed-data root.

    Support both repository-local `data/processed` and the sibling layout used
    by the other Allen VBN validation scripts.
    """
    candidates = [
        repo_root() / "data" / "processed",
        repo_root().parent / "data" / "processed",
    ]

    for candidate in candidates:
        brainset_dir = candidate / DEFAULT_BRAINSET_ID
        if brainset_dir.exists() and any(brainset_dir.glob("*.h5")):
            return candidate
        if candidate.exists() and any(candidate.glob("*.h5")):
            return candidate

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return candidates[0]


def default_metadata_csv() -> Path:
    """Default metadata CSV generated by `utils/neuron_md_gen.py`."""
    return repo_root() / "neuron_metadata" / DEFAULT_METADATA_CSV


def as_array(value: Any) -> np.ndarray:
    """Materialize lazy array-like values into a NumPy array."""
    if hasattr(value, "__array__") and not isinstance(value, np.ndarray):
        value = value[:]
    return np.asarray(value)


def as_str_array(value: Any) -> np.ndarray:
    """Normalize bytes/object arrays into plain string arrays."""
    arr = as_array(value)

    if arr.dtype.kind == "S":
        return arr.astype(str)

    if arr.dtype.kind == "O":
        return np.array(
            [x.decode("utf-8") if isinstance(x, bytes) else str(x) for x in arr]
        )

    return arr.astype(str)


def as_bool_array(value: Any) -> np.ndarray:
    """Normalize bool-like arrays from HDF5 or CSV into real booleans."""
    arr = as_array(value)

    if arr.dtype.kind == "b":
        return arr.astype(bool)

    true_values = {"true", "1", "yes"}
    false_values = {"false", "0", "no"}
    normalized = np.array([str(x).strip().lower() for x in arr])
    valid = np.isin(normalized, list(true_values | false_values))
    assert np.all(valid), f"cannot parse boolean values: {np.unique(normalized[~valid])}"

    return np.isin(normalized, list(true_values))


def scalar_to_str(value: Any) -> str:
    """Convert scalar HDF5/Data values into a plain Python string."""
    if isinstance(value, bytes):
        return value.decode("utf-8")

    arr = np.asarray(value)
    if arr.ndim == 0:
        item = arr.item()
        if isinstance(item, bytes):
            return item.decode("utf-8")
        return str(item)

    if arr.size == 1:
        item = arr.reshape(-1)[0]
        if isinstance(item, bytes):
            return item.decode("utf-8")
        return str(item)

    return str(value)


def resolve_brainset_dir(processed_dir: Path, brainset_id: str) -> Path:
    """
    Resolve a processed brainset directory from either a root or direct path.
    """
    if processed_dir.suffix == ".h5":
        return processed_dir.parent

    nested = processed_dir / brainset_id
    if nested.exists():
        return nested

    return processed_dir


def resolve_h5_paths(
    processed_dir: Path,
    brainset_id: str,
    session_id: str | None,
) -> list[Path]:
    """
    Resolve session HDF5 files for validation.

    Supports a processed root, a brainset-specific directory, or a direct HDF5
    path. If `session_id` is provided, only that session is selected.
    """
    if processed_dir.suffix == ".h5":
        assert processed_dir.exists(), f"processed HDF5 does not exist: {processed_dir}"
        return [processed_dir]

    if session_id is not None:
        direct = processed_dir / f"{session_id}.h5"
        nested = processed_dir / brainset_id / f"{session_id}.h5"

        if nested.exists():
            return [nested]
        if direct.exists():
            return [direct]

        raise FileNotFoundError(
            "Could not find processed HDF5 at either "
            f"{nested} or {direct}. Pass --processed-dir as the processed root "
            "or as the brainset-specific directory."
        )

    brainset_dir = resolve_brainset_dir(processed_dir, brainset_id)
    assert brainset_dir.exists(), f"processed brainset directory does not exist: {brainset_dir}"

    h5_paths = sorted(brainset_dir.glob("*.h5"))
    assert h5_paths, f"no HDF5 files found in {brainset_dir}"

    return h5_paths


@contextmanager
def open_data(path: Path, *, lazy: bool = True) -> Iterator[Data]:
    """Open one processed HDF5 as a temporaldata `Data` object."""
    with h5py.File(path, "r") as f:
        yield Data.from_hdf5(f, lazy=lazy)


def validate_unit_field_layout(path: Path) -> None:
    """Check optotagging unit fields exist before loading through Data."""
    with h5py.File(path, "r") as f:
        assert "units" in f, f"{path.name} is missing the units group"
        missing = REQUIRED_UNIT_FIELDS - set(f["units"].keys())
        assert not missing, f"{path.name} missing unit fields: {sorted(missing)}"


def test_standardize_genotype_labels() -> None:
    """Validate raw genotype strings map to the pipeline label vocabulary."""
    examples = {
        "Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt": "Sst",
        "sst-cre example": "Sst",
        "Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt": "Vip",
        "VIP-cre example": "Vip",
        "wt/wt": "wt",
        "Slc17a7-IRES2-Cre": "wt",
        "": "wt",
        None: "wt",
    }

    for raw_genotype, expected in examples.items():
        observed = standardize_genotype(raw_genotype)
        assert observed == expected, (
            f"standardize_genotype({raw_genotype!r}) returned "
            f"{observed!r}, expected {expected!r}"
        )

    print_ok("Genotype strings normalize to wt/Sst/Vip")


def test_make_population_psth_shape_and_binning() -> None:
    """Validate optotagging PSTH shape and pulse-relative spike binning."""
    spike_times_by_unit = {
        101: np.array([0.95, 1.02, 1.11, 1.25, 2.05, 2.15]),
        202: np.array([1.05, 1.19, 2.01, 2.22]),
    }
    unit_ids = [101, 202, 303]
    start_times = np.array([1.0, 2.0])

    psth, time_bins, returned_unit_ids = make_population_psth(
        spike_times_by_unit=spike_times_by_unit,
        unit_ids=unit_ids,
        start_times=start_times,
        time_before=0.1,
        duration=0.3,
        bin_size=0.1,
    )

    expected_time_bins = np.array([-0.1, 0.0, 0.1])
    expected = np.array(
        [
            [[10.0, 0.0], [10.0, 10.0], [10.0, 10.0]],
            [[0.0, 0.0], [10.0, 10.0], [10.0, 0.0]],
            [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0]],
        ]
    )

    assert psth.shape == (3, 3, 2), f"unexpected PSTH shape: {psth.shape}"
    assert returned_unit_ids == unit_ids, "returned unit order changed"
    assert np.allclose(time_bins, expected_time_bins), "time bin left edges changed"
    assert np.allclose(psth, expected), "pulse-relative spike binning changed"

    mean_psth, mean_time_bins, mean_unit_ids = make_population_psth(
        spike_times_by_unit=spike_times_by_unit,
        unit_ids=unit_ids,
        start_times=start_times,
        time_before=0.1,
        duration=0.3,
        bin_size=0.1,
        mean_over_trials=True,
    )

    assert mean_psth.shape == (3, 3), f"unexpected mean PSTH shape: {mean_psth.shape}"
    assert mean_unit_ids == unit_ids, "mean PSTH unit order changed"
    assert np.allclose(mean_time_bins, expected_time_bins), "mean PSTH bins changed"
    assert np.allclose(mean_psth, psth.mean(axis=2)), (
        "mean_over_trials output does not match the trial average"
    )

    print_ok("PSTH shape, binning, and trial averaging are correct")


def test_processed_h5_optotagging_unit_fields(
    h5_paths: list[Path],
) -> OptotaggingSummary:
    """Validate optotagging-specific unit fields in processed session HDF5s."""
    summary = OptotaggingSummary()

    for path in h5_paths:
        validate_unit_field_layout(path)

        with open_data(path, lazy=True) as data:
            unit_ids = as_str_array(data.units.id)
            cre_positive = as_bool_array(data.units.cre_positive)
            cell_types = as_str_array(data.units.optotagged_cell_type)
            genotype = standardize_genotype(scalar_to_str(data.subject.genotype))

            assert len(unit_ids) > 0, f"{path.name} has no saved units"
            assert len(cre_positive) == len(unit_ids), (
                f"{path.name} cre_positive length does not match units.id"
            )
            assert len(cell_types) == len(unit_ids), (
                f"{path.name} optotagged_cell_type length does not match units.id"
            )

            observed_labels = set(cell_types)
            unexpected_labels = observed_labels - ALLOWED_CELL_TYPES
            assert not unexpected_labels, (
                f"{path.name} has unexpected optotagged labels: "
                f"{sorted(unexpected_labels)}"
            )

            allowed_for_genotype = {"wt"} if genotype == "wt" else {"wt", genotype}
            incompatible_labels = observed_labels - allowed_for_genotype
            assert not incompatible_labels, (
                f"{path.name} has labels incompatible with genotype {genotype}: "
                f"{sorted(incompatible_labels)}"
            )

            summary.session_count += 1
            summary.unit_count += len(unit_ids)
            summary.genotype_session_counts[genotype] += 1
            summary.genotype_unit_counts[genotype] += len(unit_ids)
            summary.cell_type_counts.update(cell_types)
            summary.genotype_cell_type_counts[genotype].update(cell_types)

    print_ok(
        f"Validated optotagging unit fields in {summary.session_count} HDF5 files "
        f"({summary.unit_count:,} units)"
    )
    return summary


def test_dataset_level_optotagging_counts(
    summary: OptotaggingSummary,
    *,
    max_positive_fraction: float,
    require_non_wt: bool,
) -> None:
    """Validate broad global counts for genotype and optotagged cell-type labels."""
    non_wt_genotypes = sorted(
        genotype
        for genotype, count in summary.genotype_session_counts.items()
        if genotype in NON_WT_CELL_TYPES and count > 0
    )

    if require_non_wt:
        assert non_wt_genotypes, "no non-wt genotype sessions were selected"

    for genotype in non_wt_genotypes:
        genotype_units = summary.genotype_unit_counts[genotype]
        positive_units = summary.genotype_cell_type_counts[genotype][genotype]
        positive_fraction = positive_units / genotype_units

        assert positive_units > 0, (
            f"{genotype} sessions produced zero {genotype} optotagged units"
        )
        assert positive_fraction <= max_positive_fraction, (
            f"{genotype} optotagged fraction is too high: "
            f"{positive_fraction:.3f} > {max_positive_fraction:.3f}"
        )

    if non_wt_genotypes:
        counts = ", ".join(
            f"{label}={summary.cell_type_counts[label]:,}"
            for label in ["wt", "Sst", "Vip"]
        )
        print_ok(f"Global optotagging counts are within sanity bounds ({counts})")
    else:
        print_ok("No non-wt genotype sessions selected; global count check skipped")


def load_metadata_csv(metadata_csv: Path) -> pd.DataFrame:
    """Load generated neuron metadata and verify required columns exist."""
    assert metadata_csv.exists(), f"metadata CSV does not exist: {metadata_csv}"

    metadata = pd.read_csv(metadata_csv)
    missing = REQUIRED_METADATA_FIELDS - set(metadata.columns)
    assert not missing, f"metadata CSV missing fields: {sorted(missing)}"

    metadata["id"] = metadata["id"].astype(str)
    assert not metadata["id"].duplicated().any(), "metadata CSV has duplicate unit IDs"

    return metadata


def collect_h5_unit_labels(
    h5_paths: list[Path],
) -> tuple[pd.DataFrame, bool]:
    """Collect optotagging unit labels from selected session HDF5 files."""
    rows = []
    has_cre_positive = False

    for path in h5_paths:
        with open_data(path, lazy=True) as data:
            unit_ids = as_str_array(data.units.id)
            cell_types = as_str_array(data.units.optotagged_cell_type)
            session_id = scalar_to_str(data.session.id)
            subject_id = scalar_to_str(data.subject.id)

            row_data = {
                "id": unit_ids,
                "session_id": np.array([session_id] * len(unit_ids)),
                "subject_id": np.array([subject_id] * len(unit_ids)),
                "optotagged_cell_type": cell_types,
            }

            if "cre_positive" in set(data.units.keys()):
                has_cre_positive = True
                row_data["cre_positive"] = as_bool_array(data.units.cre_positive)

            rows.append(pd.DataFrame(row_data))

    return pd.concat(rows, ignore_index=True), has_cre_positive


def test_metadata_preserves_optotagging_fields(
    h5_paths: list[Path],
    metadata_csv: Path,
) -> None:
    """Validate generated metadata carries optotagging labels downstream."""
    metadata = load_metadata_csv(metadata_csv)
    h5_labels, h5_has_cre_positive = collect_h5_unit_labels(h5_paths)

    if h5_has_cre_positive:
        assert "cre_positive" in metadata.columns, (
            "metadata CSV is missing cre_positive even though HDF5 units contain it"
        )

    metadata_subset = metadata[metadata["id"].isin(h5_labels["id"])].copy()
    assert len(metadata_subset) == len(h5_labels), (
        "metadata CSV does not contain one row for each selected HDF5 unit"
    )

    metadata_subset = metadata_subset.set_index("id").sort_index()
    h5_labels = h5_labels.set_index("id").sort_index()

    assert np.array_equal(
        metadata_subset["optotagged_cell_type"].astype(str).values,
        h5_labels["optotagged_cell_type"].astype(str).values,
    ), "metadata optotagged_cell_type values do not match HDF5 labels"

    if h5_has_cre_positive:
        metadata_cre_positive = as_bool_array(metadata_subset["cre_positive"].values)
        h5_cre_positive = as_bool_array(h5_labels["cre_positive"].values)
        assert np.array_equal(metadata_cre_positive, h5_cre_positive), (
            "metadata cre_positive values do not match HDF5 labels"
        )

    print_ok(
        f"Metadata optotagging fields match {len(h5_labels):,} selected HDF5 units"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate Allen VBN optotagging labels and metadata."
    )
    parser.add_argument(
        "--processed-dir",
        type=Path,
        default=default_processed_dir(),
        help=(
            "Processed-data root, brainset-specific directory, or one session HDF5."
        ),
    )
    parser.add_argument("--brainset-id", default=DEFAULT_BRAINSET_ID)
    parser.add_argument(
        "--session-id",
        default=None,
        help="Optional session id to validate instead of all processed HDF5s.",
    )
    parser.add_argument(
        "--metadata-csv",
        type=Path,
        default=default_metadata_csv(),
        help="Neuron metadata CSV generated by utils/neuron_md_gen.py.",
    )
    parser.add_argument(
        "--max-positive-fraction",
        type=float,
        default=DEFAULT_MAX_POSITIVE_FRACTION,
        help="Maximum allowed optotagged fraction within each non-wt genotype.",
    )
    parser.add_argument(
        "--allow-no-non-wt",
        action="store_true",
        help="Allow selected HDF5s to contain no Sst/Vip genotype sessions.",
    )
    parser.add_argument(
        "--skip-metadata",
        action="store_true",
        help="Skip metadata CSV validation.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    h5_paths = resolve_h5_paths(
        processed_dir=args.processed_dir,
        brainset_id=args.brainset_id,
        session_id=args.session_id,
    )

    print(f"Validating {len(h5_paths)} Allen VBN optotagging HDF5 file(s)")

    test_standardize_genotype_labels()
    test_make_population_psth_shape_and_binning()
    summary = test_processed_h5_optotagging_unit_fields(h5_paths)
    test_dataset_level_optotagging_counts(
        summary,
        max_positive_fraction=args.max_positive_fraction,
        require_non_wt=not args.allow_no_non_wt,
    )

    if not args.skip_metadata:
        test_metadata_preserves_optotagging_fields(h5_paths, args.metadata_csv)

    print("Allen VBN optotagging validation passed!")


if __name__ == "__main__":
    main()
